comment_width = 100
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 50
error_on_unformatted = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
hex_literal_case = "Lower"
imports_granularity = "Module"
newline_style = "Unix"
normalize_doc_attributes = true
reorder_impl_items = true
struct_field_align_threshold = 50
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
#error_on_line_overflow = true
